### ISSUE TITLE
Graph API not enable in VSTS account

### ISSUE THREAD

**Issue by yaprigal** [swellaby/vsts-traffic-monitor#31]
When the task in VSTS being execute, I am getting the following error:
"An error occurred while attempting to execute the scan. Error details: Failed to retrieve the list of users from the specified VSTS account. Please ensure that the Graph API is enabled on the account."

How can I resolve the issue.
Thanks

**Comment by calebcartwright** [comment]
This extension utilizes VSTS APIs, and the [VSTS Graph API](https://www.visualstudio.com/en-us/docs/integrate/api/graph/overview) is a crucial set of APIs that the extension needs in order to function. That error message indicates that the Graph API is not available on your account.

I believe the Graph API is still in preview, but it was supposed to be rolled out to all VSTS accounts last week. This can be enabled on your account, but has to be done by a member of the VSTS Team. 

Will get back to you shortly

**Comment by calebcartwright** [comment]
@yaprigal can you provide the VSTS account name(s) of the accounts you'd like to have the Graph API enabled on? 

If you'd prefer to speak in private then send me an email opensource@swellaby.com and I'll get you in contact with someone who can enable the API on your VSTS account(s). 

Alternatively, the Graph API should be rolled out by this time next week if you'd prefer to wait.

**Comment by yaprigal** [comment]
Thanks for the quick response. closing the issue.
